name: Deploy Dalin WebSite

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Build VitePress docs
        run: npm run build

      - name: Deploy via rsync
        run: |
          sshpass -p "${{ secrets.SSH_USER_PASSWORD }}" rsync -av -e "ssh -o StrictHostKeyChecking=no -p 20001" ./dist/ ${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_SERVER_NAME }}:/home/html/multi_731459/dalin.cz/public_html